### PR TITLE
feat: stop using kubectl to apply pytorchjob

### PR DESCRIPTION
**Pull request by leseb**
79f4786 feat: stop using kubectl to apply pytorchjob

commit 79f4786ce4def68d2a3672fac0101140d1241347
Author: Sébastien Han <seb@redhat.com>
Date:   Thu Nov 21 15:23:41 2024 +0100

    feat: stop using kubectl to apply pytorchjob
    
    The PytorchJob is now running as part of the pipeline, using the
    Kubernetes library. The pod will:
    
    * load the kubeconfig
    * create the pytorchjob
    * start a watcher on pytorchjob
    * wait for the job to be done
    
    The wait will timeout after 24h just like the the kubectl used to.
    
    Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
Pipeline is doing a final run, I'll share it once done, in the meantime please review :)

**Comment by leseb** [comment]
Running here: https://rhods-dashboard-redhat-ods-applications.apps.ocp-beta-test.nerc.mghpcc.org/experiments/ilab/7e6389bc-a914-4d63-a45a-f95fbe0d5de7/runs/88ef39fe-39ca-4348-b45d-831ad35576b0

**Review by tumido — COMMENTED** [review]
Neat, however sad we didn't coordinated on this. We're currently working with RHOAI folks if/how to get `kubeflow-training` dep into the container image, so we can launch all of this as simple as:

https://github.com/kubeflow/pipelines/blob/467f30cf613ecfe181e7bf9c03cb2eef7ae1ea2d/components/kubeflow/pytorch-launcher/sample.py#L23

Let's hold of these changes and see how things work out in RHOAI.

**Comment by tumido** [comment]
> That looks great, what's the timeline for this?

I've been told by beginning of Dec.

> Why wait? We can always proceed with your proposed solution once it’s ready.

Actually.. no reason 🤷 😄 We don't have to hold off, you're right. 😄

**Comment by tumido** [comment]
Otherwise LGTM btw...

**Comment by leseb** [comment]
> Just a nit, for better UX, can we rename the `pytorchjob_manifest_[1,2]_task` to `training_phase_1,2]` task? I think it would make it much easier to understand what's going on there...

Done!

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
