### PR TITLE
fix: do not install KFP

### PR DESCRIPTION
**Pull request by leseb**
15767bb fix: bump kfp version and add jinja2 dep
044217d fix: do not install KFP on RHELAI

commit 15767bb64e32215d54cccc04effdaa7bedbdb1d8
Author: Sébastien Han <seb@redhat.com>
Date:   Thu Nov 14 11:30:36 2024 +0100

    fix: bump kfp version and add jinja2 dep
    
    - Pull the latest KFP tag.
    - Add jinja2 as a dep in Pipfile
    
    Signed-off-by: Sébastien Han <seb@redhat.com>

commit 044217d2b8b5d79735b4173f47df46e3fb8741cd
Author: Sébastien Han <seb@redhat.com>
Date:   Wed Nov 13 14:16:08 2024 +0100

    fix: do not install KFP on RHELAI
    
    KFP is part of our image so we don't need to trigger the code
    installation KFP.
    
    Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
Looking into why the python version bumped... It makes sense anyways since 3.8 is deprecated.

**Comment by leseb** [comment]
> Hmm.. KFP may be part of `RHELAI_IMAGE`, but it definitely is not present in `PYTHON_IMAGE`. 🤷
> 
> I don't think we should change every step to `RHELAI_IMAGE` though, since running 8 GB image just to list a directory in 5 seconds is nonsense...

Very good point, I totally overlooked the Python image. I also think it does not make sense to use `RHELAI_IMAGE` for everything but I believe the downstream requirement is install 0 package at runtime, so we need to find a solution to solve this.

**Comment by leseb** [comment]
Ok so for now, I have decided not to touch the components using the `PYTHON_IMAGE` and only applied `install_kfp_package=False` to the `RHELAI_IMAGE` image. Also opened https://github.com/opendatahub-io/ilab-on-ocp/issues/175 to track this.

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
